backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "ar"

collections:
  - name: "home"
    label: "الصفحة الرئيسية"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
      - label: "العنوان الفرعي"
        name: "subtitle"
        widget: "string"
      - label: "نص زر الاتصال"
        name: "cta_phone_text"
        widget: "string"
      - label: "نص زر الواتساب"
        name: "cta_whatsapp_text"
        widget: "string"
      - label: "صورة الخلفية"
        name: "background_image"
        widget: "image"
      - label: "المحتوى"
        name: "body"
        widget: "markdown"

  # المزيد من مجموعات المحتوى...
