backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

locale: "ar"

collections:
  - name: "home"
    label: "الصفحة الرئيسية"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
      - label: "المحتوى"
        name: "body"
        widget: "markdown"

  - name: "services"
    label: "الخدمات"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
      - label: "الوصف"
        name: "body"
        widget: "markdown"

  - name: "contact"
    label: "اتصل بنا"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
      - label: "الوصف"
        name: "body"
        widget: "markdown"
